title: DTWpp
description: Official documentation of DTWpp software.
remote_theme: rundocs/jekyll-rtd-theme

# Theme settings:
site_author: DTWpp authors
repo_url: "https://github.com/davidhowey/SLIDE/"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist